### PR TITLE
Fix/404 images

### PR DESCRIPTION
**Pull request by clari182**
### Fix
This fix has a migration that fixes the URLs of both broken 404 images on incident 66.
A more important fix or troubleshooting should be done in the future to discover the root of the problem. UPDATE: @lmcnulty is working on it.

### CODE REVIEW

**Comment by clari182** [comment]
Hey @smcgregor 
@lmcnulty is already working on a fix for the cause of this issue so the only thing this PR does is run a Migration to fix those specific 2 404 images.
One will change from 
`reports/images.khaleejtimes.com/storyimage/KT/20170804/ARTICLE/170809597/AR/0/AR-170809597.jpg&NCS_modified=&exif=.jpg` to `reports/images.khaleejtimes.com/storyimage/KT/20170804/ARTICLE/170809597/AR/0/AR-170809597.jpg` and work as expected.
The other one from  
`reports/s2.reutersmedia.net/resources/r/?m=02&d=20170804&t=2&i=1195770539&w=1200&r=LYNXMPED730L4` to `reports/s2.reutersmedia.net` and display the default image as I was unable to find the right image link for this.

**Review by smcgregor — APPROVED** [review]

**Comment by smcgregor** [comment]
Assigning to @cesarvarela for final review and merge.

**Review by cesarvarela — COMMENTED** [review]
Let's remove the `package-lock.json` and fix the dependency issues in another PR.

**Comment by clari182** [comment]
Closing because of new updated [PR](https://github.com/responsible-ai-collaborative/aiid/pull/861) replacing this one, without package json conflicts

**Pull request closed without merging**
