### PR TITLE
Add live option to Incidents table page

### PR DESCRIPTION
**Pull request by pdcp1**
Closes https://github.com/responsible-ai-collaborative/aiid/issues/1690

This PR makes the `/apps/incidents` page static and also adds a new option to `Show Live Data` at the top that loads the dynamic content from the DB (slower version)

Screenshot 2023-03-10 at 15 49 54

### CODE REVIEW

**Review by cesarvarela — COMMENTED** [review]
Do you have a link to test this live? Whitelisting the deploy pr URL is not working 😿

**Comment by pdcp1** [comment]
@cesarvarela this is the link to test https://deploy-preview-1720--staging-aiid.netlify.app

FYI if you temporarily disable “Drafts” on the staging Atlas app you can add a new allowed origin. Then you can enable it back and the URL will be still there 😉

**Comment by cesarvarela** [comment]
@pdcp1 

Yeah, it is already disabled in staging, but it doesn't work even if it shows it on the allowed items list :/

Feel free to give it a try. Maybe I missed something 🤔

**Review by cesarvarela — COMMENTED** [review]
There is no immediate feedback once you toggle the switch:
I toggled the switch ON, but nothing happened. Not sure if it is broken or what. 

It should show the skeleton while it loads the live data, I think.

Also, the placing of the toggle button is a bit weird, it looks like it is stuck in a random place (especially notable if you scroll the table horizontally).

**Comment by pdcp1** [comment]
@cesarvarela Done, please review.

**Pull request merged**
