### PR TITLE
Apply Flowbite Spinner component

### PR DESCRIPTION
**Pull request by pdcp1**
Pages/components changed:
- Page `/login`
- Page `/logout`
- Page `/signup`
- Page `/apps/submit` component: Image uploader
- Page `/apps/incidents` components:
  - Loading
  - Edit incident modal
- Page `/apps/submitted` components:
  - Loading submissions
  - Loading Quick Adds
  - Related incidents inside a Submission to review in "Possible related incidents" section
  - Edit report modal
- Page `/apps/discover`
- Page `/summaries/spatial` component: On the visualization graph, mouse over an item number, and a pop-up is displayed
- Page `/apps/classifications`
- Page Edit incident `/incidents/edit?incident_id=5`
- Page Edit report `/cite/edit?report_number=776`
- Page `/apps/reports`

### CODE REVIEW

**Comment by pdcp1** [comment]
@clari182 I just updated the PR description with the list of pages and components that were updated

**Comment by clari182** [comment]
Hey @pdcp1 this works as expected however there is a cypress test failing. I don't think it's related to this feature but I'd like to have all test passing before tagging this as ready to merge. Thanks!!

**Comment by pdcp1** [comment]
@clari182 Tests fixed, please review again.

**Review by clari182 — APPROVED** [review]

**Comment by cesarvarela** [comment]
@pdcp1 plase fix conflicts

**Comment by pdcp1** [comment]
@cesarvarela conflicts fixed

**Comment by cesarvarela** [comment]
@pdcp1 please do it again! The perils of big PRs

**Comment by pdcp1** [comment]
@cesarvarela done

**Comment by cesarvarela** [comment]
@pdcp1 one more time 🎶

**Comment by pdcp1** [comment]
@cesarvarela One more time, we're gonna celebrate, Oh yeah, alright, don't stop the merging 🎶

**Comment by cesarvarela** [comment]
@pdcp1 what's up with the diff here? looks like most of this has been already merged?

**Comment by cesarvarela** [comment]
Closing looks like this got merged in another PR

**Pull request closed without merging**
