### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**

### CODE REVIEW

**Comment by cesarvarela** [comment]
@smcgregor ready for review. You'll have to fix conflicts, accepting incoming should be enough.

**Comment by smcgregor** [comment]
Not blocking but needs addressing:

* The filters on the discover app still have the issue I messaged about on Slack
* When entering the incident number in the search endpoint, the search for title hangs.
* Clicking on the pie chart in the GMF taxonomy does not apply the filter that you clicked on

Still need to test

* Subscription and user cloning elements

**Comment by smcgregor** [comment]
@cesarvarela can you resolve the conflicts then I'll merge? I am on my phone for the next 16 hours (or flying).

**Comment by smcgregor** [comment]
There are differences between master and staging that are difficult to understand on my phone.

**Comment by smcgregor** [comment]
@cesarvarela updated per above.

**Comment by smcgregor** [comment]
I created a new incident on staging and added it. I'll look at the email when it comes through and merge after if it is good to go.

**Pull request merged**
