### PR TITLE
Feature/login btns 2.0

### PR DESCRIPTION
**Pull request by clari182**
- Adds Login and Sign up links to the header and left sidebar

Login link redirects to /login
Signup button redirects to /signup

Once logged in, the user's email will be displayed instead of the links (on the header and sidebar).
When clicking the email it will redirect to the /login page

### CODE REVIEW

**Comment by cesarvarela** [comment]
Is there a working preview of this one?

**Comment by cesarvarela** [comment]
@clari182 https://github.com/responsible-ai-collaborative/aiid/pull/1163/files#diff-669c71f154e5d21df106aeb41c82230771bf55c23c69c1a84e175fff5c5fa8ebL156

Please extract that change onto another PR just in case it has some undesired effect 🤔

**Comment by clari182** [comment]
@cesarvarela I remvoed that fixed and added it here #1181 
Latest preview is working: https://deploy-preview-1163--staging-aiid.netlify.app/

**Comment by cesarvarela** [comment]
There is a mystery here because this branch never passed, but this one https://github.com/responsible-ai-collaborative/aiid/pull/1181 (and some others) passed a few times already 🤔

**Comment by clari182** [comment]
@cesarvarela last deploy did pass: https://app.netlify.com/sites/staging-aiid/deploys/6334c649c18861007cb9e080

**Review by cesarvarela — COMMENTED** [review]
When on the mobile breakpoint, it shows a spinner and then it goes away, it shouldn't appear at all I think?

**Comment by pdcp1** [comment]
@clari182 As soon this [PR #1180](https://github.com/responsible-ai-collaborative/aiid/pull/1180)  is merged to Staging, we should change these two links (when the user is logged in) to point to the new `/account` page:

This link:
Screen Shot 2022-09-30 at 16 47 42

And this link as well:
Screen Shot 2022-09-30 at 16 48 24

**Comment by cesarvarela** [comment]
@clari182 #1180 is merged so you can add a link to `/accounts` now

**Review by pdcp1 — APPROVED** [review]

**Review by pdcp1 — CHANGES_REQUESTED** [review]
@clari182 We should add a test that tests the new link to `/account` page when the user is logged in. And another one that tests the case of an unauthenticated user, with the Login/Sign up links.

**Review by pdcp1 — APPROVED** [review]

**Comment by pdcp1** [comment]
The [last deploy passes](https://app.netlify.com/teams/responsible-ai-collaborative/builds/633b7b03aa88dc15e62d9c94), and the link preview to test is https://deploy-preview-1163--staging-aiid.netlify.app

It works as expected 👍 
From my side, this is ready to merge.

**Comment by smcgregor** [comment]
Sorry for being late in the game on this one. Comments!

1. Nothing in the app, especially the landing page, should draw attention (e.g., with a spinner) unless the user is meant to look there first. While this is important functionality, our opening play can't be asking them to login.
2. We want users to look at the content of the website and only log in to the app if something the user needs to accomplish requires logging in. This means we don't want users to think they will need an account on the website before they will be able to access information. Given that all our user functionality at the moment is tied to subscriptions (and to a lesser extent, non-public database editing), maybe we should scope the user account functionality to subscribing case and call the button "subscribe" rather than `login`? We can also make all user clicks go to the registration page with links to the login page since if people already have an account they will be willing to do the extra click.

**Comment by clari182** [comment]
@smcgregor I made some changes:
- Removed the spinner
- When the user is logged out the only button that appears now is "Subscribe" -> This goes to the `/signup` page (and from there if they want to login they can click on login).
- When the user is logged in the button displays "Your Account" and goes to `/account`

let me know if this is better

**Comment by smcgregor** [comment]
I think this looks good. @pdcp1 can we set a `returnTo` on the subscribe link that will then bring the user to some form of subscription page? I think you are working on a subscription notifying when new incidents come in?

**Comment by pdcp1** [comment]
@smcgregor Yes sure, we can add a `returnTo` param to the subscribe link (a.k.a. `/signup` in this case).

The possible scenarios are:

### Scenario 1 - User with account

1. The user is logged out and clicks on the `Subscribe` button
2. It redirects to `/signup?returnTo=<a_new_subscription_page>`
3. The user already has an account, so she/he clicks on "Already have an account? [Login](https://deploy-preview-1163--staging-aiid.netlify.app/login)"
4. After login, the user is redirected to `/<a_new_subscription_page>`

### Scenario 2 - User without an account

1. The user is logged out and clicks on the `Subscribe` button
2. It redirects to `/signup?returnTo=<a_new_subscription_page>`
3. The user doesn't have an account, so she/he fills the form and creates an account
4. A confirmation email is sent to the user
5. The user opens the confirmation link from the email. The account is verified.
6. At this moment we are in step 1 of Scenario 1 above

Any thoughts on this?

**Comment by pdcp1** [comment]
That sounds good to me. It makes sense to redirect the user to the account/subscription after the account verification.

I will open another issue to work on it, so we keep moving forward on this one.

**Comment by smcgregor** [comment]
@clari182 sorry I didn't get to this today, I'll review in staging!

**Pull request merged**
