### PR TITLE
Feature/tailwind cite

### PR DESCRIPTION
**Pull request by clari182**
- Part of https://github.com/responsible-ai-collaborative/aiid/issues/604
- More specifically: "Port the citation pages (e.g., https://incidentdatabase.ai/cite/1) to use Tailwind in the main content area"

### CODE REVIEW

**Review by cesarvarela — CHANGES_REQUESTED** [review]
Looks like some opacity is going haywire here: 

image


This card has a shadow but the other do not:

image

**Comment by clari182** [comment]
@cesarvarela fixed based on your comments:
- opacity
- card shadow

**Comment by cesarvarela** [comment]
please fix conflicts

**Comment by clari182** [comment]
@cesarvarela conflicts fixed

**Comment by cesarvarela** [comment]
conflicts again 🪃

**Comment by clari182** [comment]
@cesarvarela conflicts resolved!

**Review by cesarvarela — CHANGES_REQUESTED** [review]
xD

image

**Comment by clari182** [comment]
@cesarvarela fixed!

**Review by cesarvarela — APPROVED** [review]

**Pull request merged**
