### PR TITLE
Apply Flowbite Button with Spinner

### LINKED ISSUE #1061: Apply Flowbite Button with Spinner
image

Change Bootstrap Button (with spinner) component for Flowbite Button with Spinner https://flowbite-react.com/buttons

### PR DESCRIPTION
**Pull request by pdcp1**
Closes #1061 

These pages/components are changed:

- Page `/cite/5` when the user clicks on the Flag button and it opens the Flag Report modal
- Page `/apps/discover` when the user clicks on the Flag button and it opens the Flag Report modal
- Page `/apps/submit` when the user clicks on the "Fetch info" button
- Page `/cite/edit?report_number=23` when the user clicks on the "Fetch info" button
- Page `/apps/submitted` when the user clicks on buttons:
  - `Add New Incident`
  - `Add New Report`
  - `Reject New Incident`
  - `Reject New Report`

### CODE REVIEW

**Comment by pdcp1** [comment]
@clari182 please review this after merge this #1056

**Comment by cesarvarela** [comment]
@pdcp1 please fix conflicts

**Comment by pdcp1** [comment]
@cesarvarela conflicts fixed

**Review by clari182 — APPROVED** [review]

**Comment by cesarvarela** [comment]
@pdcp1 please do it again 🍷

**Comment by pdcp1** [comment]
@cesarvarela done

**Pull request merged**
