### PR TITLE
Fix variants table query

### LINKED ISSUE #2997: Variants list is not working
https://incidentdatabase.ai/apps/variants/

### PR DESCRIPTION
**Pull request by pdcp1**
Closes #2997

### CODE REVIEW

**Comment by clari182** [comment]
@pdcp1 can you fix conflicts?

**Comment by pdcp1** [comment]
@clari182 It's ready to review

**Review by clari182 — CHANGES_REQUESTED** [review]
Can you remove variants.cy ? The tests there have already been migrated to playwright. If you made any changes here, please move them to the `.spec` file. Thanks!

**Comment by pdcp1** [comment]
@clari182 
`variants.cy.js` was removed and now we are using the `playwright/e2e-full/apps/variants.spec.ts` instead.

**Review by clari182 — APPROVED** [review]

**Pull request merged**
