### PR TITLE
Feature/incidents issues variants post

### LINKED ISSUE #1463: Typeset NeurIPS Paper Blog Post
Our poster references the exact URL as stated in the paper draft: https://docs.google.com/document/d/1LYzhkA5JpjlHNB6aug5dh67SB1O_ct1bMKlAKovDl68/edit?usp=sharing

### PR DESCRIPTION
**Pull request by clari182**
Add `Indexing AI Risks with Incidents, Issues, and Variants` blog post

- closes #1463

### CODE REVIEW

**Comment by smcgregor** [comment]
Quick changes:

* The date should now read December 8th or 9th (really it should be whatever the date is when it gets merged to master)
* Markdown error: `McGregor, S., Paeth, K., & Lam, K. (2022). Indexing AI Risks with Incidents, Issues, and Variants. In Proceedings of the [NeurIPS Workshop on Human-Centered AI](https://hcai-at-neurips.github.io/site/) (NeurIPS-22). Virtual Conference.`
* The "reach out" link is broken, along with several others.
* The OECD banner should be cropped
* All the images should link to their respective reports/organizations.
* The incidents chart should link to https://incidentdatabase.ai/summaries/incidentsOverTime
* The image of the research paper should link to https://arxiv.org/abs/2211.10384

I think this is it.

**Review by smcgregor — CHANGES_REQUESTED** [review]
See comment above.

**Comment by lmcnulty** [comment]
No need to hold on merging for it, but I included alt-text for the images in https://github.com/responsible-ai-collaborative/aiid/pull/1472 that you might want to copy over.

**Comment by smcgregor** [comment]
@clari182 ok, merging now so we can get it into prod.

**Pull request merged**
