### PR TITLE
New Incident Variants UX

### PR DESCRIPTION
**Pull request by pdcp1**
Closes https://github.com/responsible-ai-collaborative/aiid/issues/1779

### Preview link: https://deploy-preview-16--pablocosta-staging.netlify.app/apps/variants/

The preview link for a Cite with a variant: https://deploy-preview-16--pablocosta-staging.netlify.app/cite/464/

### CODE REVIEW

**Comment by pdcp1** [comment]
@smcgregor Could you write a field description for the `Inputs / Outputs` tooltip, please?

Screenshot 2023-04-10 at 13 41 22

**Comment by smcgregor** [comment]
* It looks like the code block is breaking the width of the cards, click on "ChatGPT produces made-up nonexistent references"
* "Description of Incident Circumstances: Journalistic reporting on the circumstances of the incident to help inform people what happened, where, involving who, when, and why."
* "Inputs / Outputs: The sequence of data inputs into the intelligent system and outputs produced by the system involved in the incident. For a chatbot, this will generally present a back and forth between a human and the chatbot's responses."

**Review by cesarvarela — COMMENTED** [review]
I'm getting an error when submitting a new variant:
```
{"data":{"createVariant":null},"errors":[{"message":"reason=\"role \\\"default\\\" in \\\"aiidprod.reports\\\" does not have insert permission: unspecified fields in document: [epoch_date_modified authors date_published epoch_date_published source_domain epoch_date_downloaded inputs_outputs date_modified language title date_downloaded date_submitted cloudinary_id text image_url plain_text url tags is_incident_report submitters report_number epoch_date_submitted]\"; code=\"ArgumentsNotAllowed\"; untrusted=\"insert not permitted\"; details=map[]","locations":[{"line":2,"column":3}],"path":["createVariant"]}]}
```

The variants table is empty. Not sure if that's expected.

**Comment by pdcp1** [comment]
@cesarvarela please review. A rule on reports was missing and now I added it.

**Pull request merged**
