### PR TITLE
Fix translations discrepancies

### PR DESCRIPTION
**Pull request by pdcp1**
This PR addresses all discrepancies in translations and resolves any missing translations found in https://incidentdatabase.ai/meta/i18n

### Preview link
https://pr-3219--staging-aiid.netlify.app/meta/i18n

### Result

image

### CODE REVIEW

**Review by clari182 — APPROVED** [review]

**Review by clari182 — CHANGES_REQUESTED** [review]
@pdcp1 can you change "disrepencies" to "discrepancies"? Otherwise PR looks good!

**Comment by pdcp1** [comment]
> @pdcp1 can you change "disrepencies" to "discrepancies"? Otherwise PR looks good!

@clari182 done!

**Comment by pdcp1** [comment]
Hi @technohippy, 

Since you were the one who initially added the first Japanese translations to the system, could you please take a look at the changes in the `JA` folder https://github.com/responsible-ai-collaborative/aiid/pull/3219/files? We would really appreciate your feedback on whether those translations make sense to you. Thank you!

**Review by clari182 — APPROVED** [review]
Approved! Waiting on @technohippy review of `ja` to merge.

**Pull request merged**
