### PR TITLE
Add view full incident version modal

### PR DESCRIPTION
**Pull request by pdcp1**
This closes https://github.com/responsible-ai-collaborative/aiid/issues/2242

### CODE REVIEW

**Review by cesarvarela — COMMENTED** [review]
Can you try to get the deploy passing?

**Review by cesarvarela — COMMENTED** [review]
Sometimes it is not using the modal full width:

image


Not related, but this should show a user name instead.

image

**Review by cesarvarela — COMMENTED** [review]
Seems like editor names are missing:

image


Maybe it should also render the timeline?

**Comment by cesarvarela** [comment]
I think this should render the Cite template in its fullest to be really full :P

**Review by cesarvarela — COMMENTED** [review]
Should we hide the right sidebar? It looks weird otherwise:

image

It is missing user first/last names when using anonymous users, maybe show a placeholder, like `Redacted` or something like that 🤔

**Review by cesarvarela — COMMENTED** [review]
We should hide the editor since you are not able to edit old version classifications:
image

**Review by cesarvarela — CHANGES_REQUESTED** [review]
What do these empty squares mean?

https://deploy-preview-2248--staging-aiid.netlify.app/incidents/history/?incident_id=559

image

**Comment by pdcp1** [comment]
> What do these empty squares mean?

@cesarvarela It's because the entities `test` on that history record doesn't exist on the `entities` collection.

image

Probably because of a previous DB restore from Production using the Github action.
I just realized that the `Restore Prod DB into Staging` Github action doesn't restore the `history` database.

**Comment by cesarvarela** [comment]
> I just realized that the Restore Prod DB into Staging Github action doesn't restore the history database.

I wonder if it should though 🤔

**Review by cesarvarela — APPROVED** [review]

**Pull request merged**
