### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**

### CODE REVIEW

**Comment by cesarvarela** [comment]
@kepae ready for review

fyi @smcgregor

**Review by kepae — APPROVED** [review]
🎊

**Comment by kepae** [comment]
Let's hold off merging this until tomorrow morning -- Sean forwarded me an email he received from staging:
"Your submission has been approved!"

Wondering if the submission collection migration for user fields (https://github.com/responsible-ai-collaborative/aiid/pull/2239) triggered this. Don't want to trigger a production set of emails unintentionally.

**Comment by cesarvarela** [comment]
I think @pdcp1 was playing with the promote thing

**Comment by pdcp1** [comment]
@kepae Yes, it was me testing on Staging

**Pull request merged**
