### PR TITLE
Feature/tailwind css - step1 - installation 

### PR DESCRIPTION
**Pull request by clari182**
- From issue #604 
Implements: Install TailwindCSS https://tailwindcss.com/docs/guides/gatsby

### CODE REVIEW

**Comment by cesarvarela** [comment]
It is weird that this is missing package-lock changes 🤔

**Review by cesarvarela — CHANGES_REQUESTED** [review]
This should include package-lock changes

**Comment by clari182** [comment]
@cesarvarela Package lock added

**Review by cesarvarela — APPROVED** [review]
Looks good, next to be merged after the i18n stuff is out

**Pull request merged**
