### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
This PR updates old packages, so the `--legacy-peers-flag` is not necessary anymore 🥳, and fixes hydration errors across the site (there are still some, like in the landing page, but I've tracked them down to a few components);

To get this PR working on production, the following environment variables need to be updated:

Add:

```
AWS_LAMBDA_JS_RUNTIME=nodejs18.x
NODE_VERSION=18
NODE_OPTIONS=--max-old-space-size=4096
```

Remove:

```
NPM_FLAGS
NPM_VERSION
```

This also leaves us at the door of upgrading to Gatsby v5.

### CODE REVIEW

**Comment by cesarvarela** [comment]
@smcgregor ready for review

**Comment by smcgregor** [comment]
Things seem to load faster. Lots of minified react errors though. The hydration fixes are independent of this?

**Comment by cesarvarela** [comment]
Those minified react errors are hydration errors; I've tracked them down to a few components on the landing page on what would be considered the content area. I'll push a fix for those on another pr.

**Comment by smcgregor** [comment]
OK, can you update the parameters on Netlify and ping me to hit the merge button here?

**Comment by cesarvarela** [comment]
@smcgregor done!

**Pull request merged**
