### PR TITLE
Simplify submission form

### PR DESCRIPTION
**Pull request by lmcnulty**
- Builds on https://github.com/responsible-ai-collaborative/aiid/pull/805
- Adds more descriptive placeholders per #984 
- Collapses description, tags, editor notes, developer, deployer, and harmed parties under `<details>` element
  - Should eventually become a two-step submission, per #849.

The RelatedIncidentsArea now slides in instead of appearing suddenly:

https://user-images.githubusercontent.com/25443411/189949064-3cdf4e6a-90a9-4f3d-a7fc-03f5bb8056aa.mp4

### CODE REVIEW

**Comment by clari182** [comment]
@lmcnulty looks great!
The only thing I see is that the placeholder `Who experienced negative impacts` should be `Who experienced negative impacts?`
Also, maybe we should consider adding a tooltip for developer, deployer and harmed parties because those are also entered under the format "values separated by commas". Maybe we could add a tooltip there to explain this.

**Comment by lmcnulty** [comment]
@clari182 Since we were planning to move away from using CSV for multi-input (#955), instead of adding instructions for the CSV values, I switched to the tag input and added some minimal instructions there.

I've also added the relevant keys to the Spanish localization files – they still need to be translated.

**Comment by clari182** [comment]
@lmcnulty yes, that's way better.

Here are the translations that way they can be merged with this PR. 

```
"harmed_parties": {
       "title": "Partes presuntamente perjudicadas o casi perjudicadas",
       "text": "Si son múltiples, presione "enter" después del elemento para ingresar uno nuevo"
     },
     "deployers": {
       "title": "Presunto implementador del sistema de IA",
       "text": "Si son múltiples, presione "enter" después del elemento para ingresar uno nuevo"
     },
     "developers": {
       "title": "Presunto desarrollador del sistema de IA",
       "text": "Si son múltiples, presione "enter" después del elemento para ingresar uno nuevo"
     }
```

**Comment by lmcnulty** [comment]
Thanks! I realized that a few translations were still missing. In `submit.json` there are:

```json
  "Who created or built the technology involved in the incident?": "",
  "Who employed or was responsible for the technology?": "",
  "Who experienced negative impacts?": ""
  "Your name as you would like it to appear in the leaderboard": "",
  "The author or authors of the report": "",
  "Description": "",
  "Report description": "",
  "Tags": ""
  "Tell us more...": ""
```

**Comment by clari182** [comment]
@lmcnulty there you go!
```
 "Who created or built the technology involved in the incident?": "¿Quién creó o construyó la tecnología involucrada en el incidente?",
  "Who employed or was responsible for the technology?": "¿Quién utilizó o fue responsable de la tecnología?",
  "Who experienced negative impacts?": "¿Quién experimentó impactos negativos?"
  "Your name as you would like it to appear in the leaderboard": "Tu nombre de la forma que te gustaría que apareciera en la clasificación",
  "The author or authors of the report": "El autor o autores del informe",
  "Description": "Descripción",
  "Report description": "Descripción del informe",
  "Tags": "Etiquetas"
  "Tell us more...": "Cuéntanos más..."
```

**Comment by lmcnulty** [comment]
@clari182 Thanks! I think it's ready now.

**Review by clari182 — APPROVED** [review]

**Comment by cesarvarela** [comment]
Since you are at it, I think this looks really weird, I wonder if it could be improved, maybe with a smaller preview in the same row as the Image Address input field?

image

**Comment by lmcnulty** [comment]
@cesarvarela I had made it smaller previously, but it looks like that got undone in the tailwind migration. I'm setting it back to how it was (with inline styles since there seem to be bootstrap/tailwind conflicts here).

image

**Comment by cesarvarela** [comment]
@lmcnulty can you please merge `staging` here, maybe we get to see some green

**Pull request merged**
