### PR TITLE
Add editor notes to incidents

### LINKED ISSUE #2033: Add Editor's Notes Section to Incident Profiles
Editors need some place where they can optionally put notes about the incident and display those notes to users. This should be a new markdown text field attached to the incidents collection and conditionally displayed on the citation pages when there is content in the field.

### PR DESCRIPTION
**Pull request by clari182**
- closes #2033 

Deploy preview: https://deploy-preview-15--clarayoudale-staging.netlify.app/

### CODE REVIEW

**Comment by clari182** [comment]
Hey @smcgregor, let me know if this is what you had in mind for the editor notes. You can edit it when editing an incident and also view under the description on the citation page. Example : https://deploy-preview-15--clarayoudale-staging.netlify.app/cite/10/#r23

**Comment by smcgregor** [comment]
This looks good to me. I'll share the PR with the editor's slack channel and see if there are any comments there.

**Review by smcgregor — APPROVED** [review]

**Review by cesarvarela — CHANGES_REQUESTED** [review]
Please update the appropriate tests!

**Comment by clari182** [comment]
Hey @cesarvarela here's is the latest deploy of this on my env:
https://app.netlify.com/sites/clarayoudale-staging/deploys/6480a39dcb6c0c04e1e3837a

Here's the deploy preview https://deploy-preview-15--clarayoudale-staging.netlify.app/

**Review by cesarvarela — APPROVED** [review]

**Pull request merged**
