### PR TITLE
add epoch fields to incident report updates

### PR DESCRIPTION
**Pull request by smcgregor**

### CODE REVIEW

**Comment by smcgregor** [comment]
@cesarvarela I attempted to add the epoch fields to the backend function, but this is the proper place to introduce the epoch updates. I believe something is still blocking the update. Can you review this and let me know what needs to change?

**Comment by cesarvarela** [comment]
The issue is that the epochs don't get updated when changing the dates?

**Comment by cesarvarela** [comment]
The issue is that the epochs don't get updated when changing the dates?

**Comment by cesarvarela** [comment]
Seems to be working?

image

**Comment by smcgregor** [comment]
Which code were you running?

**Comment by cesarvarela** [comment]
I think the schema changes weren't pushed to Realm so that's why it isn't working for you.

**Comment by smcgregor** [comment]
Were you running this pull request and when Realm updated properly this merge request works for you?

**Comment by cesarvarela** [comment]
Seems so.

**Comment by smcgregor** [comment]
Should I merge?

**Review by cesarvarela — APPROVED** [review]

**Comment by cesarvarela** [comment]
Yes 👍

**Pull request merged**
