### PR TITLE
Filter variant reports from incident list display (closes  #1593)

### LINKED ISSUE #1593: Variant: causes empty report item in incident list
When viewing the entire list of incidents (https://incidentdatabase.ai/summaries/incidents), I noticed that [Incident 464](https://incidentdatabase.ai/cite/464) has just an empty bullet/list item. This appears to be the variant report 2587, shown in the incident profile.

image

The relevant HTML is below, the `data-cy` attribute pulling an empty or malformed report 2587 to form a new bullet.

```
<h2>
  Incident 464
  <a role="button" tabindex="0" href="/cite/464" class="btn btn-outline-primary"
    >Citation</a
  ><a
    role="button"
    tabindex="0"
    href="/apps/discover?incident_id=464"
    class="btn btn-outline-primary"
    >Discover</a
  >
</h2>
<div class="text-xl">
  “ChatGPT Provided Non-Existent Citations and Links when Prompted by Users”
</div>
<ul class="pl-8 leading-6 my-4 list-revert">
  <li data-cy="report-2584">
    <a href="https://news.ycombinator.com/item?id=33841672"
      >ChatGPT produces made-up nonexistent references</a
    >
  </li>
  <li data-cy="report-2585">
    <a href="https://openai.com/blog/instruction-following/"
      >Aligning Language Models to Follow Instructions</a
    >
  </li>
  <li data-cy="report-2586">
    <a href="https://analyticsindiamag.com/why-is-everyone-bashing-chatgpt/"
      >Why is Everyone Bashing ChatGPT?</a
    >
  </li>
  <li data-cy="report-2587"><a href=""></a></li>
</ul>
```

I noticed that the incident profile (?) has an unnamed variant displayed at the bottom. It seems to be the alleged report 2587 (`id="r2587"`). HTML from incident profile page:

```
<h1>Variants</h1>
<div class="mb-4">
  A "variant" is an incident that shares the same causative factors, produces
  similar harms, and involves the same intelligent systems as a known AI
  incident. Rather than index variants as entirely separate incidents, we list
  variations of incidents under the first similar incident submitted to the
  database. Unlike other submission types to the incident database, variants are
  not required to have reporting in evidence external to the Incident Database.
  <a href="https://arxiv.org/abs/2211.10384"
    >Learn more from the research paper.</a
  >
  <div class="flex flex-col gap-3 mt-5">
    <div
      id="r2587"
      data-cy="variant-card"
      class="relative p-4 overflow-hidden flex tw-card border-1 rounded-lg break-words flex-col shadow-lg"
    >
      <div class="flex">
        <div
          data-cy="variant-status-badge"
          class="bg-blue-100 text-blue-800 dark:bg-blue-200 dark:text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded capitalize"
        >
          unreviewed
        </div>
      </div>
      <div class="flex w-full flex-col mt-3 gap-2">
        <div class="font-bold flex items-center gap-2">
          Input and circumstances
          
[..]
```

This could potentially be folded into Variant Support (#1283).

### PR DESCRIPTION
**Pull request by kepae**
Fix for https://github.com/responsible-ai-collaborative/aiid/issues/1593.
Need to test it (which involves rectifying my npm package problems), therefore WIP/draft.

### CODE REVIEW

**Comment by cesarvarela** [comment]
Are you using `--legacy-peer-deps`?

**Comment by kepae** [comment]
Yep, I am now! I needed to clear the `npm` cache to make it work:

`npm cache clean --force`
`npm install --legacy-peer-deps` 

However, running fresh Gatsby for the first time in months and I'm getting (new to me) GraphQL errors. Will look into this and see if it's my fresh dev setup somewhere.

```
ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Field "is_incident_report" is not defined by type
"mongodbAiidprodReportsFilterInput".

File: gatsby-node.js:79:13

GraphQLError: Field "is_incident_report" is not defined by type "mongodbAiidpr
  odReportsFilterInput".
```

**Comment by cesarvarela** [comment]
A `mongorestore` of the latest db should fix that.

**Comment by cesarvarela** [comment]
To elaborate, that error is most likely because you don't have a `report` in your DB with the `is_incident_report` field.

Going deeper, the `gatsby-source-mongodb` plugin infers a graphql schema from the mongo database. For the `reports` collection, it creates a few graphql queries, including `mongodbAiidprodReportsFilterInput,` which creates graphql filters based on the collection's fields.

Or maybe it is caused by something different :)

**Comment by kepae** [comment]
Thanks Cesar -- the updated `.env` creds in https://github.com/responsible-ai-collaborative/aiid/pull/1603 fixed my issues.

One additional commit -- now the graphQL also requests `report.text_inputs` and `report.text_outputs`, which are needed in order for `hasVariantData()` to distinguish the variants from regular reports. 
However, this could become inefficient very fast if these fields have larger payloads in the future. I haven't looked into the schema, but an `is_variant` field might be the answer.

Screenshot below. The spurious empty variant report under Incident 464 is gone, and all other reports remain.

image

**Comment by kepae** [comment]
I'm noting that I should probably update this to target the staging branch and sync, which I'll do when I'm at my computer next (this weekend). Anyone should feel free to crib this and submit of course.

**Comment by smcgregor** [comment]
I updated the base.

**Pull request merged**
