### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
- reorder snapshots
- promote submissions to issues

### CODE REVIEW

**Comment by cesarvarela** [comment]
@smcgregor issues feature is merged if you want to review

**Comment by cesarvarela** [comment]
@lmcnulty looks like something went wrong with the new canonical URL stuff. Can you check, please?

**Comment by lmcnulty** [comment]
@cesarvarela Fixed by #1412.

**Comment by cesarvarela** [comment]
@smcgregor this is ready for another review

**Comment by smcgregor** [comment]
@cesarvarela thanks, have you updated the staging DB lately to match current production?

**Comment by cesarvarela** [comment]
@smcgregor It's been a a while, I can do it if you want

**Comment by smcgregor** [comment]
It looks like you cleaned out the issue reports I ingested before, which was what I was worried about. I am going to ingest things now on staging and give it a thorough test.

**Comment by smcgregor** [comment]
### Non-blocking issues

These issues won't prevent us from deploying to production, but there are some bad ones that will greatly increase the time needed to ingest the full backlog of issues.

- [ ] When I clicked "add issue" on the oldest report in the review queue, I receive the error below. To fix it, I had to un-assign an incident from the report and then give it an incident date.
Screen Shot 2022-11-28 at 7 48 12 PM

- [ ] The issue above seems to be the standards case -- when I submit a new report without incident data it gets blocked.

- [ ] Multiple fields that are related to incidents must be input before it will allow for updating a report that is in the review queue, even if it will be added as an issue.

**Comment by smcgregor** [comment]
I triggered a new build after adding a few issue reports. If it passes, I'll merge it.

**Comment by smcgregor** [comment]
The build passes, but I am not seeing any content here: https://staging-aiid.netlify.app/apps/discover/?display=details&is_incident_report=false&page=1

@cesarvarela I don't see Algolia mentioned in the build output. Is it not pushing the index?

https://app.netlify.com/sites/staging-aiid/deploys/6385839da69c55455b656475

**Comment by smcgregor** [comment]
## Blocking

- [ ] The Algolia build test is failing https://app.circleci.com/pipelines/github/responsible-ai-collaborative/aiid/60/workflows/f67fdaf9-33ff-4111-b51a-6dea626d7359/jobs/118?invite=true#step-104-93

**Pull request merged**
