### PR TITLE
Manually keep track of connections

### LINKED ISSUE #2816: Mongo connections not being recycled when serving from gatsby develop or gatsby serve
I think it could be what is causing this:

image

And some crashes when running `gatsby devevelop` locally.

### PR DESCRIPTION
**Pull request by cesarvarela**
closes #2816  (hopefully this time)

### CODE REVIEW

**Comment by pdcp1** [comment]
@cesarvarela I got the error `500 Internal Server Error` on each `/graphql` call on the preview link.
For example, loading this report edit dynamic page 
https://pr-2824--staging-aiid.netlify.app/cite/edit/?report_number=1994&incident_id=322

**Review by pdcp1 — CHANGES_REQUESTED** [review]
https://github.com/responsible-ai-collaborative/aiid/pull/2824#issuecomment-2155394477

**Comment by cesarvarela** [comment]
@pdcp1 give it a nother try

**Comment by pdcp1** [comment]
@cesarvarela The `/graphql` endpoint calls return `200` now.

But when I try to edit a report (e.g.: https://pr-2824--staging-aiid.netlify.app/cite/edit/?report_number=1994&incident_id=322 ) I got a blank page.
However, the same page on staging works fine: https://staging-aiid.netlify.app/cite/edit/?report_number=1991&incident_id=322

This is the Rollbar error on this PR preview: https://app.rollbar.com/a/seanbmcgregor/fix/item/AIID/6723

FYI: Incident edition page works fine 👍

**Comment by cesarvarela** [comment]
Turns out aliases were broken 🤯 

There are some reports of this same issue in the graphq-tools repo:

https://github.com/ardatan/graphql-tools/issues/5262

Using `stichSchemas` instead of `mergeSchemas` fixes it so 🤷

**Comment by cesarvarela** [comment]
@pdcp1 ready for another round

**Review by pdcp1 — APPROVED** [review]

**Pull request merged**
