### PR TITLE
Change `editor` role to `incident_editor`

### PR DESCRIPTION
**Pull request by pdcp1**
Part of the https://github.com/responsible-ai-collaborative/aiid/issues/2383

### CODE REVIEW

**Review by cesarvarela — COMMENTED** [review]
Looks like this line still references the old role:

https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/cypress/e2e/integration/apps/submitted.cy.js#L73

**Review by cesarvarela — APPROVED** [review]

**Comment by kepae** [comment]
@pdcp1 if this is good to do, ping either César or I when you'd like to merge this to staging, given the migration?

**Comment by pdcp1** [comment]
I'm good to merge this into Staging. Let me know so I can check if the migration works as expected.

**Comment by pdcp1** [comment]
The migration works as expected on Staging 👍

**Pull request merged**
