### PR TITLE
Restore tsne to sidebar, show all incidents

### PR DESCRIPTION
**Pull request by lmcnulty**
The embedding update workflow now runs on production, so the TSNE visualization can be made visible. This also fixes an issue where only the first 100 incidents were shown:

### CODE REVIEW

**Comment by cesarvarela** [comment]
Does this run on staging too?

**Comment by lmcnulty** [comment]
@cesarvarela Yes, it should. It's actually already rendering on staging: https://staging-aiid.netlify.app/summaries/spatial.

**Comment by cesarvarela** [comment]
@lmcnulty  Yes, but I mean the automatic action

**Comment by lmcnulty** [comment]
Oh, sorry. No, the workflow doesn't run on staging.

**Pull request merged**
