### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by smcgregor**

### CODE REVIEW

**Comment by smcgregor** [comment]
@cesarvarela This is almost ready to deploy, but I encountered a breaking issue.

1. Go to https://deploy-preview-298--staging-aiid.netlify.app/cite/1
2. Click on one of the bubbles with "4" in it.
3. It will crash on Chrome and Safari
4. On Safari, it also will not scroll to the report when clicking on a specific report

**Comment by smcgregor** [comment]
No. It is working on the popup (when there are multiple timeline entries), but it is not scrolling at all for the single entries on the timeline. `Version 14.1.2 (15611.3.10.1.5, 15611)`. Can you click around a bit more to try and replicate and I'll update my Safari?

**Comment by cesarvarela** [comment]
I can confirm on 14. Working on it

**Comment by cesarvarela** [comment]
I think this will fix it https://github.com/PartnershipOnAI/aiid/pull/308

**Pull request merged**
