### PR TITLE
Edit forms: Restore "fetch info," multi-line inputs

### LINKED ISSUE #1378: Editor submission form – Missing `Fetch info`
"Please re-instate `Fetch info` button. Quite often, it is used by me to get the clean text of old reports in the queue, or of new reports submitted by new users who are not familiar with our standards for text"

image

### PR DESCRIPTION
**Pull request by lmcnulty**
Closes #1378 and #1379.

image

image

## Breakage Attempts

- Check that "Fetch info" appears and works on edit form from submission queue and `/cite/edit`
- Check that submitting with those fields filled works
- Check that description and editor notes field has handle on Firefox and Chromium

### CODE REVIEW

**Comment by LKchemposer** [comment]
@lmcnulty I want to confirm that this PR also restore the `Fetch Info` button in the form where editors decide whether to ingest a report or not – i.e., the form used in the review queue. Also, are there official names for these different things?

**Comment by lmcnulty** [comment]
@LKchemposer Yes, it affects both the forms on `/cite/edit` and `/apps/submitted`. 

I'm not sure there's an official name. In the code, the component containment hierarchy is:
`/apps/submitted` > `SubmissionList` > `SubmissionReview` > `SubmissionEditModal` > `SubmissionForm`

Probably the clearest way to refer to it is by a description of the component and the URL path where it's found. E.g. "The edit modal on `/apps/submitted`."

image

**Comment by LKchemposer** [comment]
@lmcnulty, that would be clear for the developer folks, but for normies who only interact with the UX – like me, I think something a bit more natural language would be helpful. How about:

| Form name | path | Editable by | Key info |
| - | - | - | - |
| submit form | ??? | submitters | 3-step process, incident fields not required for new incidents |
| ingest form | `/apps/submitted` | editors | in the review queue, facilitate adding to db |
| edit form | `cite/edit` | editors | in the citation page, to rectify report fields |
| table form | ??? | editors | in the table view, to rectify incident fields |

**Comment by cesarvarela** [comment]
@lmcnulty no test needs update after this? 🤔

**Comment by lmcnulty** [comment]
@cesarvarela I don't think this changes any of the tested behaviors. I added another test that the button works.

**Comment by cesarvarela** [comment]
@lmcnulty please fix conflicts

**Comment by smcgregor** [comment]
@lmcnulty conflicts, when fixed I'll merge.

**Pull request merged**
