### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by kepae**

### CODE REVIEW

**Comment by smcgregor** [comment]
🫡 (yay to no longer being the default user)

**Comment by cesarvarela** [comment]
I've been playing around with the new Submission UI and got an error when assigning an editor, but it isn't showing here:

https://rollbar.com/seanbmcgregor/all/items/?sort=%5Bobject%20Object%5D&status=active&date_from=&date_to=&environments=staging&activated_to=&framework=&levels=40&levels=50&activated_from=&offset=0&timezone=America%2FMontevideo&assigned_user=&date_filtering=seen&projects=500413&query=&enc_query=

It would be nice to be sure we are properly tracking errors before merging since this is a new feature.

**Comment by kepae** [comment]
@cesarvarela @clari182 Agree, we would especially like to know if editors hit problems. Why wouldn't errors get logged by rollbar?

I also don't see any errors for staging at all in rollbar. I rotated the token in https://github.com/responsible-ai-collaborative/aiid/issues/2279 but I wasn't using rollbar prior, and don't know if ifs new/old that there are no errors there.

**Comment by cesarvarela** [comment]
This line sends the error to Rollbar, so my guess is that there is a token problem yup.

https://github.com/responsible-ai-collaborative/aiid/pull/2295/files#diff-4e040be5c7c9fd9f759d67e5c1f0aa4d435c8596a52c25ec4b62e9133d7ceb7cR115

@pdcp1 might know exactly why it isn't being logged.

**Comment by pdcp1** [comment]
@cesarvarela You're right. Rollbar logs are not working on Staging. I'm checking what's happening.

**Comment by pdcp1** [comment]
@kepae Just to confirm, which Rollbar project did you get the token from?
Is it https://app.rollbar.com/a/seanbmcgregor ?

**Comment by kepae** [comment]
@pdcp1 Yes, exactly. However, I'm thinking I used the wrong "scope" for token -- they work differently between projects and accounts. I used `write`, not `post_client_item`. I'll update accordingly.

**Comment by kepae** [comment]
I switched from `write` to `post_client_item` in staging, prod, and the empty netlify environments. I'll kick off another staging build to deploy that in staging.

**Comment by pdcp1** [comment]
Update from Rollbar issue.
I found that we have a console error on Staging (the same happens on my localhost) related to CORS.

```
Access to script at 'https://cdn.rollbar.com/rollbarjs/refs/tags/v2.26.1/rollbar.min.js' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
image

**Comment by kepae** [comment]
@cesarvarela Want to try and reproduce errors again in staging, now that rollbar is back to life?

**Comment by cesarvarela** [comment]
Couldn't reproduce it.

But I'm noticing now that invalid fields are not getting highlighted in red. In this case, the Incident Title field should have the red outline:

image

Like it does in the submission form:


image

**Comment by kepae** [comment]
Hmm. I think it's best to fix that before releasing, since it's core to the editor checks.
On the other hand, we can provide an FYI to editors and go ahead -- provided we fix it later this week.

@clari182 your thoughts?

**Comment by clari182** [comment]
@kepae I'll provide a fix shortly

**Pull request merged**
