### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by smcgregor**

### CODE REVIEW

**Comment by smcgregor** [comment]
@lmcnulty it looks like the fetch info button is broken in staging now. Can you take a look?

**Comment by smcgregor** [comment]
I'll merge something small to staging and see what happens.

**Comment by smcgregor** [comment]
No joy. I am not sure where the server-side log for this function lives -- it is not coming up in Netlify/MongoDB. Anyone know where to look?

**Comment by lmcnulty** [comment]
`/api/semanticallyRelated` also seems to be immediately 500ing.

**Comment by smcgregor** [comment]
Merging this. I'll peg the deploy to an older version and make the API breakage a daybreaker if it then also breaks prod.

**Pull request merged**
