### PR TITLE
Migrate rss.cy and signup.cy to Playwright

### LINKED ISSUE #2905: Migrate rss.cy tests to Playwright

### LINKED ISSUE #2906: Migrate signup.cy tests to Playwright

### PR DESCRIPTION
**Pull request by clari182**
- closes #2905 
- closes #2906

### CODE REVIEW

**Review by cesarvarela — CHANGES_REQUESTED** [review]
Plese use the `e2e-full` folder insteadm and test against the seed data

**Comment by cesarvarela** [comment]
@clari182 please merge staging

**Comment by clari182** [comment]
@cesarvarela done, ready for new review

**Comment by clari182** [comment]
@cesarvarela can you review this please?

**Pull request merged**
