### PR TITLE
Fix/Submission Form: hide description when incident id

### PR DESCRIPTION
**Pull request by clari182**
- part of #1346
Solves:

> When adding a report for an existing incident, the description field is still visible. It should be hidden if the incident already exists.

### CODE REVIEW

**Review by cesarvarela — CHANGES_REQUESTED** [review]
This change warrants a new test or an update to an existing one.

**Comment by clari182** [comment]
@cesarvarela test added

**Comment by cesarvarela** [comment]
@clari182 ditto from other prs 😆

**Comment by clari182** [comment]
@cesarvarela conflicts fixed!

**Review by cesarvarela — APPROVED** [review]

**Pull request merged**
