### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
A `GATSBY_ROLLBAR_TOKEN` env variable needs to be created before merging

### CODE REVIEW

**Comment by cesarvarela** [comment]
@smcgregor can you try to fix conflicts? It is not picking up my latest merge attempting to fix them.

**Comment by smcgregor** [comment]
I can take a look, can you give me more context and details?

**Comment by cesarvarela** [comment]
@smcgregor I think this is some bug with GitHub's diffing getting confused; it should be easy to fix from the web UI.

It is only this line:

image

(we should remove that test or use an entity that changes less often, but the conflicts need to be fixed anyway)

**Comment by smcgregor** [comment]
ok, so I should update my local copy of staging and master, merge master to staging, then push directly to staging?

**Comment by cesarvarela** [comment]
yes exactly that

**Comment by smcgregor** [comment]
Done.

**Comment by cesarvarela** [comment]
@smcgregor ready for review

Among other things, it contains fixes for the current production deploy and CSET tool improvements.

**Comment by smcgregor** [comment]
@cesarvarela will this work if the rollbar token is not set? We need to announce this a bit louder, if so.

Created: https://github.com/responsible-ai-collaborative/aiid/issues/2081

I have not tested the CSET tool updates, but I will ask CSET to give it a test after this merges.

**Comment by cesarvarela** [comment]
@smcgregor it will, it just won't track errors.

**Pull request merged**
