### PR TITLE
Make parseURL function work for other namespaces

### LINKED ISSUE #2381: Discover – Parse URLs for all taxonomy namespaces
In reviewing https://github.com/responsible-ai-collaborative/aiid/pull/2350, there is a TODO in the `parseURL.js` logic indicating we need to improve the logic to handle all possible taxonomy namespaces:

```javascript
for (const attr in obj) {
    if (stringKeys.includes(attr) && obj[attr] !== undefined) {
      // TODO: we have to make the other namespaces available here too
      if (obj[attr].indexOf('CSET') >= 0) {
        // The facet separator is double pipe sign - "||"
        newObj[attr] = obj[attr].split('||CSET').map((i) => 'CSET' + i);
        newObj[attr][0] = newObj[attr][0].substr(4);
      } else {
        newObj[attr] = obj[attr].split('||');
      }
    }
  }
  return newObj;
};
```

### PR DESCRIPTION
**Pull request by clari182**
- closes #2381

### CODE REVIEW

**Review by pdcp1 — CHANGES_REQUESTED** [review]
Please add tests for this change

**Review by pdcp1 — CHANGES_REQUESTED** [review]

**Comment by cesarvarela** [comment]
This is being tackled on in #2467

**Comment by pdcp1** [comment]
> This is being tackled on in #2467

Got it! Approved it then

**Review by pdcp1 — APPROVED** [review]

**Comment by clari182** [comment]
@cesarvarela this PR is good to merge

**Comment by cesarvarela** [comment]
I don't think this will be necessary after #2467 

If it is, we can reopen

**Pull request closed without merging**
