### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
To get the workflow working these variables need to be added to the GitHub staging environment:
```
DB_PRODUCTION_CONNECTION_STRING=[Production connection string with readonly user credentials. ie: mongodb+srv://[DB readonly user]:[DB user password]@aiiddev-xxxxxx.gcp.mongodb.net]
DB_STAGING_CONNECTION_STRING=[Staging connection string with admin user credentials. ie: mongodb+srv://[DB admin user]:[DB user password]@aiiddev-xxxxxx.gcp.mongodb.net]
NETLIFY_BUILD_STAGING_URL=[Netlify Staging build hook. This value is on https://app.netlify.com/sites/staging-aiid/settings/deploys#continuous-deployment]
```

### CODE REVIEW

**Comment by cesarvarela** [comment]
@pdcp1 we already have a few environment variables that change based on the branch:

image

Maybe call them something like: `MONGODB_RESTORE_CONNECTION_STRING` to avoid confusion? Or should we delete them and reuse the same two for everything?

@smcgregor, what do you like more? A connection string per functionality or a couple used everywhere?

**Comment by smcgregor** [comment]
Connection string per auth level maybe?

**Comment by smcgregor** [comment]
I am having trouble identifying what env changes are needed on this one. Are they only needed if we hit the restore button?

**Comment by smcgregor** [comment]
@clari182 I think there is a plain text attribute you could put in the feed rather than the Markdown. The markdown won't render properly in readers.

I still need to play with the submit form and understand the environment variables, but am otherwise 👍

**Comment by cesarvarela** [comment]
@smcgregor Yes only needed to get the restore button working. Nothing will break if not set.

**Comment by smcgregor** [comment]
Submit form worked fine for me, including the local storage drafts. :)

I don't want to merge this until the RSS feed is updated to the plain text or we decide we are not doing that. @clari182 thoughts?

**Pull request merged**
