### PR TITLE
Feature/tailwind discover

### PR DESCRIPTION
**Pull request by clari182**
Part of https://github.com/responsible-ai-collaborative/aiid/issues/604
- Port the incident report cards on the Discover application to use Tailwind (https://incidentdatabase.ai/apps/discover)

Bootstrap elements to convert later:
- Form
- Modal

### CODE REVIEW

**Review by cesarvarela — CHANGES_REQUESTED** [review]
broken

image

**Comment by clari182** [comment]
@cesarvarela fixed conflicts and styling issues. Ready for review again

**Comment by cesarvarela** [comment]
@clari182  Still broken:

image

**Comment by cesarvarela** [comment]
This one on the default view, doesn't look intentional 🤔 
image

**Comment by clari182** [comment]
@cesarvarela I fixed this. It looks like it was a specific issue for Safari where links with type button were rendered with borders, like buttons.

**Review by cesarvarela — APPROVED** [review]

**Pull request merged**
