### PR TITLE
Fix/refactor submission approved

### LINKED ISSUE #2473: Improve submission-promoted code
We are currently using a subscription and a notification for `submission-promoted` emails.
To simplify (and avoid future issues), we should simplify this and only create a notification. Since this is only triggered once and the subscription is no longer needed.

The notification would need to have a new field called userId only used for this kind of scenario where a notification doesn't need a subscription

### PR DESCRIPTION
**Pull request by clari182**
- closes #2473 
Preview: https://deploy-preview-34--clarayoudale-staging.netlify.app/

### CODE REVIEW

**Review by pdcp1 — APPROVED** [review]
The code LGTM and the functionality work as expected in Clara's environment

**Comment by pdcp1** [comment]
@cesarvarela @kepae This PR should be merged **after** this one https://github.com/responsible-ai-collaborative/aiid/pull/2459 because this last one has a test code refactor.

**Comment by clari182** [comment]
I merged staging and there were some conflicts so another review is suggested

**Review by pdcp1 — COMMENTED** [review]
@clari182 did you explicitly change the `/functions/processNotifications.js` file or are the changes part of the Staging merge? 
I have the same question for `processNewPromotionsNotifications.cy.js` file.

**Comment by clari182** [comment]
@pdcp1 I explicitly changed them. For `/functions/processNotifications.js` I added the check to only send emails to unique userIds, this was done for the other subscriptions but not for `submittion-promoted`. The other change in that file seems to be a formatting one which I can remove if you want.
For `processNewPromotionsNotifications.cy.js` I had to update the tests in order to adapt to the code change.

**Review by pdcp1 — APPROVED** [review]
LGTM. After merging this into Staging we should do a test there.

**Comment by kepae** [comment]
Stellar. Let's merge and test, and we'll re-enable notifications for this push.

**Pull request merged**
