### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
- table views translations
- typo
- sender name in emails
- fix some hydration errors (more to be fixed #1624 
- fix variants list
- resize timeline viz
- TSNE page updates
- discover sorting options
- small UI fixes

### CODE REVIEW

**Comment by cesarvarela** [comment]
@clari182 the `Should sort by published date` test seems to be failing.

**Comment by cesarvarela** [comment]
@smcgregor, new stuff landed, ready for review.

**Comment by smcgregor** [comment]
This looks great. I found there was a report that was erroneously tagged as published in 2029. I fixed that in prod...

Shall I merge?

**Comment by smcgregor** [comment]
@clari182  It looks like sorting by newest/oldest submitted date is returning the same content.

**Comment by cesarvarela** [comment]
@smcgregor fix merged

**Pull request merged**
