### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
Pushing this one change alone.
* #2700 
* #2742

### CODE REVIEW

**Comment by cesarvarela** [comment]
Lets wait for this [one](https://github.com/responsible-ai-collaborative/aiid/pull/2743) to work before pushing.

**Comment by cesarvarela** [comment]
@kepae did some smoke testing and everything seems to be working

**Comment by kepae** [comment]
Happy to push tonight, but perhaps tomorrow is better when I'm more available. Just let me know.

**Comment by cesarvarela** [comment]
yes tomorrow sounds better

**Comment by kepae** [comment]
@cesarvarela Pushing!

**Review by kepae — APPROVED** [review]

**Pull request merged**
