### PR TITLE
Added draft probes.ts file in e2e directory as per issue

### PR DESCRIPTION
**Pull request by scottslewis**
Added draft probes.ts file in e2e directory as per issue

https://github.com/responsible-ai-collaborative/aiid/issues/2886

The probe tests in probes.ts use the (new) pages-tests.ts/testUrls utility function (which is a generalized version of the previous pages-tests.ts/testPages.

I've tried to have these tests be somewhat similar to the tests in pages?.spec.ts.  Someone may want to refactor the tests for organization and desired consistency, I'm +1 for any renaming/refactoring/etc that is desired.

I don't know how/when it's desired to run these tests, and so need to consult with team about that before changing the config and/or github actions appropriately.

### CODE REVIEW

**Review by cesarvarela — COMMENTED** [review]
- I would create a new folder to keep these tests separate, it should be inside `/playwright/probes` (or similar)
- the base URL should be read from the environment variable `SITE_URL` that I'm introducing here https://github.com/responsible-ai-collaborative/aiid/pull/3103/files#diff-d5171f9b8c42863b1e934fda1fefedf968913c65aa5d715555a696fb3cbd4c7eR98
- a new GitHub workflow is needed to run these tests separately. It can get inspiration from `.github/workflows/test-playwright.yml`

**Comment by kepae** [comment]
@cesarvarela @scottslewis I would suggest that for a start, we can hard-code (or declare a list of constants) the site URLs we wish to test.

This acts how a _user_ would act, which is the purpose of the probe.

But yes -- we should move this to `/playwright/probes` (out of `e2e`).

**Comment by scottslewis** [comment]
Hi guys

On Tue, Oct 8, 2024, 12:22 PM Kevin ***@***.***> wrote:

> @cesarvarela <https://github.com/cesarvarela> @scottslewis
> <https://github.com/scottslewis> I would suggest that for a start, we can
> hard-code (or declare a list of constants) the site URLs we wish to test.
>
I'm fine for this and cesars dir/org changes.

But question on this one (constants):  I would be inclined to make one list
constant in probes.ts with all probes (for now)...and have a single test
method (again for now).   This does however have side effect of having no
time (or/login/config etc) between probes done in sequence.  This doesnt
sim user very well but ok for now?  Other test cases can/will then be added
for auth, config, etc probes to be added.

**Comment by kepae** [comment]
@scottslewis Responding to your comment here to keep it close to the code review. :-)
> https://github.com/responsible-ai-collaborative/aiid/issues/2886#issuecomment-2415265835
>In commit: https://github.com/scottslewis/aiid/commit/199ddaeeea49efa38ebc8af0aedc99d394fd66aa
>
>I've moved probes.ts to a new directory (e2e/probes/) and refactored the tests so that there is one const 2-dim array that >defines the tests and now have only one test method. That test method now iterates through the array to call testUrl >(urlPrefix, paths) for each url prefix/paths combination defined in urls1.
>
>Feel free to make any desired stylistic or doc changes.


* The probe tests are still under the existing `playwright/e2e/` directory. This directory is used for build-time (and soon-to-be) hermetic tests. I suggest moving it to `/playwright/probes` (out of `e2e`).
  * It wasn't easy for me to confirm this, it _is_ buried in the workflow files:
    * Non-hermetic (i.e. contain mocks still) tests: https://github.com/responsible-ai-collaborative/aiid/blob/ed115cbb5fdb6858c22692edf0c8d8a4ebfabede/.github/workflows/test-playwright.yml#L91
    * Hermetic tests (no mocks! all in-memory! all under our controls!): https://github.com/responsible-ai-collaborative/aiid/blob/ed115cbb5fdb6858c22692edf0c8d8a4ebfabede/.github/workflows/test-playwright-full.yml#L136
  * In a follow-up, we'll set up a workflow that runs these probes completely independently of our build. :-) 
  
* Iteration of a once-defined list of URLs to test is great. Can we iterate through them in a way such that each separate test is a distinct playright test? That way when one "probe" fails and other succeed, we can more easily tell. Right now, I believe they're all tested in serial within the same test.
  * Looking at Playwright, this would be a parameterized test: https://playwright.dev/docs/test-parameterize#parameterized-tests ->
```js
[
  { name: 'Alice', expected: 'Hello, Alice!' },
  { name: 'Bob', expected: 'Hello, Bob!' },
  { name: 'Charlie', expected: 'Hello, Charlie!' },
].forEach(({ name, expected }) => {
  // You can also do it with test.describe() or with multiple tests as long the test name is unique.
  test(`testing with ${name}`, async ({ page }) => {
    await page.goto(`https://example.com/greet?name=${name}`);
    await expect(page.getByRole('heading')).toHaveText(expected);
  });
});
```

Lastly, please sync this PR with your changes so that they appear in the UI in this repo (`responsible-ai-collaborative/aiid`) and not just your fork (https://github.com/scottslewis/aiid/commit/199ddaeeea49efa38ebc8af0aedc99d394fd66aa). That way we can comment in line using the review UI.
I will also mark this PR as "ready for review" since we are in the throes now. 

Looking forward to green probes!

**Comment by scottslewis** [comment]
> @scottslewis Responding to your comment here to keep it close to the code review. :-)
> 
> 
>     * The probe tests are still under the existing `playwright/e2e/` directory. This directory is used for build-time (and soon-to-be) hermetic tests. I suggest moving it to `/playwright/probes` (out of `e2e`).
>       
Moved to /playwright/probes

>       * In a follow-up, we'll set up a workflow that runs these probes completely independently of our build. :-)
> 
>     * Iteration of a once-defined list of URLs to test is great. Can we iterate through them in a way such that each separate test is a distinct playright test? That way when one "probe" fails and other succeed, we can more easily tell. Right now, I believe they're all tested in serial within the same test.

Sure.   Done.

Here's the new pr #3161 

Closing this pr.

**Pull request closed without merging**
