### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
- new taxonomies

**Because of migrations, we'll need to disable/enable triggers before merging into production**

### CODE REVIEW

**Comment by cesarvarela** [comment]
@lmcnulty looks like there is a leftover `publish` query in the `createTsneVisualizationPage` function.

**Comment by cesarvarela** [comment]
It is here, https://github.com/responsible-ai-collaborative/aiid/blob/staging/site/gatsby-site/gatsby-node.js#L150
It needs to be updated to the new classifications schema.

**Comment by cesarvarela** [comment]
@lmcnulty looks like `/apps/classifications` is broken; not sure exactly why: https://staging-aiid.netlify.app/apps/classifications/

**Comment by cesarvarela** [comment]
@lmcnulty there is another error now:

image

**Comment by cesarvarela** [comment]
@lmcnulty looks like it is still broken

image

**Comment by cesarvarela** [comment]
There was another item with null. After manually editing it, the app loads.

image

`incident_id: 6` and `Quality Control` the field.

**Comment by cesarvarela** [comment]
It works now 🎉

**Comment by smcgregor** [comment]
@cesarvarela made it to hotel -- should deploy or wait?

**Pull request merged**
