### PR TITLE
Add localized link to (?) icon in similar incidents

### PR DESCRIPTION
**Pull request by lmcnulty**
Fixes issue in https://github.com/responsible-ai-collaborative/aiid/issues/917

### CODE REVIEW

**Comment by cesarvarela** [comment]
woot I'm working on these! The only one I'm missing is to show the translated titles on the similar incidents cards:

image

Not sure if this is possible tho, are those the titles of the incident or some of the reports linked to the incident?

**Comment by lmcnulty** [comment]
Not sure if you're still looking for this, but those are the titles of the incidents. They should all have titles by now, but if one of them doesn't it falls back to the title of the first report.

**Comment by cesarvarela** [comment]
@lmcnulty then we should show the incident title as it was before when the selected language it is not English, because we don't have translations for it yet, something like here:

https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/src/templates/cite.js#L136

Can you work on that?

**Comment by cesarvarela** [comment]
Closing because this is being dealt with in #918  (the comment above still applies though)

**Comment by lmcnulty** [comment]
@cesarvarela Ok, I'm on it.

**Comment by cesarvarela** [comment]
thanks 🙏

**Pull request closed without merging**
