### PR TITLE
Switch to table on /summaries/flagged

### LINKED ISSUE #941: The flagged incident list uses colons instead of table columns
colon-as-table

### PR DESCRIPTION
**Pull request by lmcnulty**
Resolves #941.

image

### CODE REVIEW

**Comment by clari182** [comment]
Hey @lmcnulty looks good on desktop however on lower resolutions the table goes out of the main layout
image
image

**Comment by lmcnulty** [comment]
@clari182 It now switches to a single-column on mobile.

 

For consistency, I've also removed the tabs to switch between description and text and just made `text` a scrolling field to avoid taking up too much space.

**Review by clari182 — APPROVED** [review]
Code looks good, works as expected

**Comment by cesarvarela** [comment]
Would like to see green marks before merging, can you merge staging again just in case please?

**Comment by lmcnulty** [comment]
@cesarvarela Done.

**Pull request merged**
