### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
- tailwind & bootstrap scoping (means we can use tailwind freely, and bootstrap can be limited only to forms)
- email-password/facebook signups
- menu restructuring
- TSNE visualization

### CODE REVIEW

**Comment by cesarvarela** [comment]
This is almost ready to go live:

@lmcnulty can you write the steps needed before and after (when applicable) to get the TSNE viz running on production please?

@pdcp1 same but for the signup page

Thanks

**Comment by pdcp1** [comment]
The steps to get the Signup page feature running on productions are:

For **Facebook integration**, follow this guide https://www.mongodb.com/docs/atlas/app-services/authentication/facebook/#std-label-auth-facebook-app-setup
In summary:

Before merge:
- Create a Facebook App - type Consumer
- Enable Facebook Login - From the app's Dashboard view, find the Facebook Login card and click Set Up
- Under Facebook Login settings, add `https://stitch.mongodb.com/api/client/v2.0/auth/callback` to Valid OAuth Redirect URIs list
- Under Roles, add Pablo, Cesar, Clara, and Luna as app Administrators

After merge:
- On Atlas Service App, the Facebook Authentication provider should be created automatically after the deploy
- On Facebook Authentication settings, set the "Client ID" with the Facebook App Id. To get the Facebook App ID you should go to the [Facebook Developer Portal](https://developers.facebook.com/apps/), and check your app.
- Add this secret value to your Atlas App Service following the instructions in the [Atlas App Services documentation](https://www.mongodb.com/docs/atlas/app-services/values-and-secrets/define-and-manage-secrets/).
  - `facebookAppSecret` To get the Facebook App Secret you should go to the [Facebook Developer Portal](https://developers.facebook.com/apps/), and click on your app > Settings > Basic.

For **Google Integration**, follow this guide https://www.mongodb.com/docs/atlas/app-services/authentication/google/#std-label-google-authentication
In summary:

Before merge:
- Create a Project in the Google API Console
- Generate OAuth Client Credentials. Go to your Console > APIs & Services > Credentials > Create Credentials > 
OAuth client ID
  - Application type: `Web Application`
  - Authorized JavaScript origins: `https://realm.mongodb.com`
  - Authorized redirect URIs: `https://stitch.mongodb.com/api/client/v2.0/auth/callback`
 
After merge:
- On Atlas Service App, the Google Authentication provider should be created automatically after the deploy
- On Google Authentication settings, set the "Client ID" with the Google Client ID (OAuth 2.0 Client ID). In order to get the Google Client ID (OAuth 2.0 Client ID) you should set up an OAuth 2.0 following these [instructions](https://support.google.com/cloud/answer/6158849?hl=en). After set it up, you can find the Google Client ID in your [Google Cloud Console](https://console.cloud.google.com/apis/credentials).
- Add this secret value to your Atlas App Service following the instructions in the [Atlas App Services documentation](https://www.mongodb.com/docs/atlas/app-services/values-and-secrets/define-and-manage-secrets/).
  - `googleClientSecret ` To get the Google Client Secret you should go to [Google Cloud Console](https://console.cloud.google.com/apis/credentials), and click on the OAuth 2.0 Client ID item.

**Comment by lmcnulty** [comment]
The only step required to get the TSNE visualization running should be to run the `state_update_db.py` from the nlp-lambdas repo. I think you've already done that correctly for staging, but to be explicit:

1. Clone the repo

    ```bash
    git clone https://github.com/responsible-ai-collaborative/nlp-lambdas.git
    cd nlp-lambdas/
    ```

2. (optional) Create a [Python virtual environment](https://virtualenv.pypa.io/en/latest/).

    If it's not already installed, you can install virtualenv with:

    ```bash
    python3 -m pip install --user virtualenv
    ```

    (You might have python 3 installed as just `python`, but on Debian-based systems it's `python3`, so that's what I'm using.)

    ```bash
    python3 -m virtualenv -p python3 env-aiid-nlp
    
    source env-aiid-nlp/bin/activate
    ```
    After you run `source`, your shell prompt should be prefixed by `(env-aiid-nlp)` and running `python` and `pip` will use the Python version installed in your virtual environment.

4. Install the python dependencies

    ```bash
    pip install -r requirements.txt
    pip install -r requirements-dev.txt
    ```

5. Install the language model. **Warning**: this will download several gigabytes of data.
    ```bash
    git submodule update --init --recursive
    ```

6. Run the `state_update_db.py` script, providing the appropriate MongoDB connection string as an environment variable:

    ```bash
    MONGODB_CONNECTION_STRING=mongodb+srv://<USER>:<PASSWORD>@<CLUSTER>.mongodb.net python state_update_db.py
    ```
    It will probably print out:
    ```
    Some weights of the model checkpoint at inference/model were not used when initializing LongformerModel: ['lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.decoder.weight', 'lm_head.bias']
    - This IS expected if you are initializing LongformerModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
    - This IS NOT expected if you are initializing LongformerModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model)
    ```
    You can ignore it. It should then start printing:
    ```
    checking 1
    checking report 4
    checking report 9
    checking report 12
    checking report 11
    checking report 3
    checking report 14
    checking report 6
    checking report 5
    checking report 1
    checking report 8
    checking report 10
    checking report 2
    checking report 15
    checking report 7
    uploading embedding for incident 1
    checking 2
    checking report 142
    checking report 141
    …
    ```
    This will take a while. If you stop it or get a connection error, you can run it again and it will resume from where it left off.

    In the MongoDB UI, you should see an `embedding` field containing a long list of numbers added to incidents:
    
    

    After you build the site, there should also be a TSNE field added:

**Comment by smcgregor** [comment]
Preliminary review below, I'll take a deeper review after the blockers are addressed.

## Blocking Deploy

- [ ] @pdcp1 the login/out functionality now gives people the ability to create user accounts, but it looks like those user accounts are getting permissions that they should not have. Specifically, users that create their own accounts should not be able to see the elements displayed below on the citation pages, and they should not have permission to edit anything. I think all new user accounts may be getting provisioned super user privileges?

Empty classifications should not display in the UI,
Screen Shot 2022-08-31 at 2 50 44 PM


- [ ] Merge `master` into `staging` (a few hotfixes landed)

## Not Blocking

- [ ] When `1st report only` is turned on and the page is reloaded (or the URL is shared), the setting is not sticky.
- [ ] The salience of the language switcher could be reduced, possibly by making the button be an outline rather than filled in
- [ ] The spatial visualization page needs the following updates:

```
Spatial Visualization
The visualization below shows incidents closer together when a [natural language processing system](https://staging-aiid.netlify.app/blog/using-ai-to-connect-ai-incidents) identifies their text as being semantically similar.

Color by incident classifications from taxonomies
```

- [ ] We are starting to have more dynamically populated content from the database. We either need to upgrade our systems to have lower latency, or we need to make sure all the static query stuffs are properly in place. I am mostly thinking of the TSNE visualization at present since we are going to start featuring it, and things like it, more fully.
- [ ] After the login functionality is set up, will it read "AI Incident Database" (see below for what Google currently displays)?

Screen Shot 2022-08-31 at 2 42 30 PM

- [ ] The registration activity likely needs a "return to" URL since we will roll out account registration with the subscription feature.

**Comment by pdcp1** [comment]
> * I think all new user accounts may be getting provisioned super user privileges?

@smcgregor you're right, all new users are set with the `admin` role. I will change the `onNewUser` function to set `subscriber` role as a default role.
Do we have a list of roles and their privileges defined? Looking at the code I see these but we should define them:
- admin
- incident_editor
- submitter
- taxonomy_editor
- taxonomy_editor_<namespace>
- subscriber

**Comment by smcgregor** [comment]
admin: All the permissions. God Mode.
incident_editor: Can edit incidents
submitter: No special permissions. Really the same as unauthenticated.
taxonomy_editor: Can edit a taxonomy.
subscriber: Can subscribe to emails

Some of these are redundant and can likely be eliminated. The roles are largely forward looking and everything has broadly assumed admin powers.

**Comment by pdcp1** [comment]
> Empty classifications should not display in the UI,

@smcgregor The code explicitly hides the Taxonomy Classifications sections if they are empty, but it displays them if the user has the role `taxonomy_editor` so he/she can click on the "Edit" button.
For example, a user with `subscriber` role won't see empty classifications, but a user with `admin` or `taxonomy_editor` role will do.

**Comment by pdcp1** [comment]
> * After the login functionality is set up, will it read "AI Incident Database" (see below for what Google currently displays)?

@smcgregor I didn't find a quick solution for that. I found these posts (without an answer) that talks about the same issue.
- https://www.mongodb.com/community/forums/t/changing-the-web-site-named-in-the-login-window-message-choose-an-account-to-continue-to-mongodb-com/156404
- https://www.mongodb.com/community/forums/t/google-oauth-consent-screen-shows-mongodb-com/564

The problem is that Realm integration needs the `https://stitch.mongodb.com/api/client/v2.0/auth/callback` URI in the Authorized redirect URIs list, and Google takes the domain of that URI to display in the consent screen.
We have to research more on this matter to see if we can change that `mongodb.com` company name to `AI Incident Database` with a Google App validation.

**Comment by pdcp1** [comment]
> * The registration activity likely needs a "return to" URL since we will roll out account registration with the subscription feature.

@smcgregor Added in this PR https://github.com/responsible-ai-collaborative/aiid/pull/1051

**Comment by smcgregor** [comment]
Thanks @pdcp1 ! Your roles breakdown makes sense to me.

That redirect naming issue is rough. In the absence of a quicker fix, I am inclined to hide Google until subscription support is up.

**Comment by pdcp1** [comment]
> That redirect naming issue is rough. In the absence of a quicker fix, I am inclined to hide Google until subscription support is up.

@smcgregor I decided to hide the Google Authentication by now until the brand name is supported. I subscribed to the Atlas App services forum posts to be aware of any updates.
@cesarvarela Please review this PR with this changes https://github.com/responsible-ai-collaborative/aiid/pull/1054

**Comment by smcgregor** [comment]
@lmcnulty Do you think the [GitHub hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) are strong enough to run the steps you have posted above? This looks like something that should be in a cron-triggered GitHub workflow.

**Comment by lmcnulty** [comment]
@smcgregor The nlp-repository, model, and dependencies together weigh 6.1G, so 14 GB should be enough disk space. I think I remember it also using 6ish GB of RAM, so we'll be cutting it close to the 7 GB limit, but it's probably worth a try.

**Comment by smcgregor** [comment]
@lmcnulty please give it a try. We may need to establish an environment we control to run this sort of job, but let's only do that when forced to.

**Comment by smcgregor** [comment]
@cesarvarela How are we looking for this deploy? Production is getting stale.

**Comment by cesarvarela** [comment]
@smcgregor two outstanding issues:

-  running the TSNE process on a GitHub box which I think @lmcnulty is working on it
- custom email for signups which @pdcp1 is working on

I can make a quick PR hiding this things so we can deploy in the meantime

**Comment by lmcnulty** [comment]
@cesarvarela @smcgregor 

> running the TSNE process on a GitHub box which I think @lmcnulty is working on it

I believe the TSNE workflow is ready, it just needs [the pull request on nlp-lambdas](https://github.com/responsible-ai-collaborative/nlp-lambdas/pull/22) merged and the corresponding secret added. If someone with access to the production DB could manually run the script, I think that would also unblock this deploy, since automatic updating is not essential to the feature.

**Comment by cesarvarela** [comment]
@smcgregor this should be ready to deploy

**Comment by pdcp1** [comment]
@smcgregor I see that https://github.com/responsible-ai-collaborative/aiid/actions/runs/3057071170/jobs/4931853562 failed because `facebookAppSecret` secret value is missing on Prod

**Comment by smcgregor** [comment]
I hit retry after looking at the instructions in the readme and adding the secret in MongoDB's app services.

https://app.netlify.com/sites/aiid/deploys/63229d30b96f0b4818d05fc1

**Pull request merged**
