### PR TITLE
Add Algolia as In-kind Sponsor

### PR DESCRIPTION
**Pull request by clari182**
- Issue #997 

[Deploy preview](https://deploy-preview-1003--staging-aiid.netlify.app/)

- Algolia was added as an In-kind sponsor with text provided in the issue
- I also changed the sponsors' design a little bit to differentiate more each section
- Refactor sponsors sections to avoid duplicated code for each sponsor
- Border around sponsor's document (issue mentioned in #929)

### CODE REVIEW

**Comment by cesarvarela** [comment]
I think it would look better if all logos had the same height:

image

**Comment by smcgregor** [comment]
Looks good. A few comments,

- Let's put the border around the founding report as mentioned here: https://github.com/responsible-ai-collaborative/aiid/pull/929

- I had a typo on the issue, improving the text: `[Algolia](https://algolia.com/) provides the Responsible AI Collaborative with an instant search index of incident reports.`

- Let's also make the logos on the modals click through to the organization's websites.

**Comment by clari182** [comment]
@smcgregor 
- Logos have the same height
- Border back on the left section (let me know if it's ok like this I didn't remember how it was before)
- Typo fixed
- Modals' logo click goes to site
- I also refactor the sponsors section, let me know if this is ok like this.

**Comment by smcgregor** [comment]
I am going to share this deploy preview with Algolia per their request, this looks good to me except the border you put in place is different from the border I was referring to. You can't reference production anymore to see what it was like before since production includes the tailwinds changes, but you can see it in this screen capture from https://62ffd12404b7660008110499--aiid.netlify.app/

The boarder is around the image of the document and is in place to reinforce that it is a document.

Screen Shot 2022-08-24 at 4 11 28 PM

**Comment by clari182** [comment]
@smcgregor border added around the document

**Review by smcgregor — APPROVED** [review]

**Comment by smcgregor** [comment]
Algolia is go! Approving on my end.

**Review by cesarvarela — APPROVED** [review]

**Pull request merged**
