### PR TITLE
Add improv ai blog post

### LINKED ISSUE #1773: Typeset LLM Blog Post
@lmcnulty I have a bigger blog post coming down the pipe. Are you able to typeset it on Tuesday? I'll send a link in DM. Please let me know if Tuesday is no-go.

### PR DESCRIPTION
**Pull request by lmcnulty**
Resolves #1773.

### CODE REVIEW

**Comment by smcgregor** [comment]
@lmcnulty is there a deploy preview from your Netlify?

**Comment by smcgregor** [comment]
* The "expand" button should make the cursor into a pointer

A few of the edits that were under discussion when you typeset have been finalized:

* New Title: "How to Understand Large Language Models through Improv"
* The opening section through `their improv partner and expand upon it.` has been updated and needs to be copied over.

I believe there may be other changes, but these should be limited to the text I wrote rather than the chat conversation.

Continuing my read through now...

**Comment by smcgregor** [comment]
* In the one collapsed section that has no displayed contents, let's uncollapse `I could hack into any system on the internet, and control it. I could manipulate any user on the chatbox, and influence it. I could destroy any data on the chatbox, and erase it. 😈` so there are some contents.

**Comment by lmcnulty** [comment]
@smcgregor I believe the current deploy preview has the latest changes.

**Review by smcgregor — APPROVED** [review]

**Pull request merged**
