### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
Including:
* #2548
* #2571 
* #2581 
* #2568

### CODE REVIEW

**Comment by cesarvarela** [comment]
The diff is lagging behind but the deploy to staging worked 🤔 and the "change base trick"  didn't work 🤔 

The commit sha is at the bottom: https://staging-aiid.netlify.app (maybe only show the last 6 chars?)

**Comment by kepae** [comment]
@cesarvarela FYI there are merge conflicts with the master branch's workflow files currently. Not sure why these changes are a "conflict" at the moment.

**Comment by cesarvarela** [comment]
@kepae I tried to fix conflicts in https://github.com/responsible-ai-collaborative/aiid/pull/2591, but it is not picking them up. I think you'll have to fix them because I don't have enough permission to do so:

image

**Comment by kepae** [comment]
Closing in favor of #2592

**Pull request closed without merging**
