### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**

### CODE REVIEW

**Comment by cesarvarela** [comment]
@smcgregor ready for review

**Comment by smcgregor** [comment]
@pdcp1 it looks like this will automatically subscribe the editor to the submission they add to an incident? I didn't notice the subscription work landing. Can you also set the submitting user to subscribe if there is a submitting user?

Merging this now.

**Comment by pdcp1** [comment]
@smcgregor This automatically subscribes the **Submitter** of the submission (if there is a submitter user) to the incident just created (or the existing incident associated with the new report).
Is that what you mean?

**Comment by smcgregor** [comment]
Yes, it looks like I misread the code. Thanks!

**Pull request merged**
