### PR TITLE
Restructuring

### PR DESCRIPTION
**Pull request by lmcnulty**
Addresses #851 and #954.

- Moves documentation links to the footer, now in a columnar layout

  image

- Adds icons to the sidebar items

  

  - The blog stays in the sidebar. Even though it's documentation of sorts, it's intended for the general public and we have space for it currently.

- Rearranges the taxonomy page template to put the first graph above the fold.
  - It would be nice to eventually incorporate the list of categories we use as links to the discover app into the graph itself.
  
  image

- ~~"Taxonomies" link in sidebar goes directly to CSET~~
  - ~~Header contains a link to `/taxonomies` for switching and learning about how we use taxonomies.~~
  - ~~I think going directly to a display of an implemented taxonomy with graphs, etc. will be more engaging than hiding it behind the taxonomies list. People are more likely to care about what taxonomies are available once they've seen one.~~
    - ~~Perhaps we could add a dropdown menu to switch between taxonomies?~~
    - In revision, I've instead added a carousel containing some of the more interesting charts under the CSET bullet on the /taxonomies page.
      
      https://user-images.githubusercontent.com/25443411/186501120-87cbc50b-c8c1-4dd7-8ea0-e3d6f4f32c5b.mp4

### CODE REVIEW

**Comment by smcgregor** [comment]
* Design looks good in the screen captures you provide.
* Please link the taxonomies nav to the taxonomies page as it currently exists. CSET is working on a V2 that would deprecate the V1 and @npit is working on another taxonomy as well. Linking directly to a single taxonomy compromises this element of flexibility we are looking to emphasize. I think a better solution to the problem you are highlighting is to have cards/short panels that are graphical and can display on the current taxonomy listing. Maybe presenting the most informative pie chart in a card presentation?

**Comment by cesarvarela** [comment]
Please merge staging now that deploy finishes 🥳

**Comment by cesarvarela** [comment]
@lmcnulty please fix conflicts, and now that #1001 is merged please remove all `tw` prefixes.

**Comment by lmcnulty** [comment]
@cesarvarela Done.

**Comment by lmcnulty** [comment]
@cesarvarela Fixed.



I had to set the sidebar ul padding to 0 with inline styles, because bootstrap css was overriding the tailwind classes.

**Comment by cesarvarela** [comment]
`Should submit a new report not linked to any incident once all fields are filled properly`

It is failing and it is usually not flaky I believe. Can you make sure it is not failing because something else  broke?

**Comment by cesarvarela** [comment]
The test should use `data-cy=toast` anyway, I'll merge and if it is broken fix it in another PR

**Pull request merged**
