### PR TITLE
Run tests on GitHub

### LINKED ISSUE #667: Run tests on Github
- [x] deploy previews
- [x] #2540
- [x] #2541
- [x] #2542
- [x] #2543
- [x] #2214
- [x] #2587
- [x] #2600

### PR DESCRIPTION
**Pull request by pdcp1**
This PR adds a new Github Action called `Cypress e2e tests`

### ⚠️ Important note before merging
As soon this PR is merged to staging, a new Github action will be created and a set of Github secrets (ENV variables) should be created on the repo.
Please check the `README` file to get the Github secret variables.

Closes #667

### CODE REVIEW

**Review by cesarvarela — CHANGES_REQUESTED** [review]
Wait you still need the netlify.toml file to deploy on Netlify!

Also if tests fail will the Netlify deploy still happen?

**Comment by pdcp1** [comment]
> Wait you still need the netlify.toml file to deploy on Netlify!
> 
> Also if tests fail will the Netlify deploy still happen?

@cesarvarela `netlify.toml` file is back 👍 
Currently, the tests and the deploy execute in parallel, so if the tests fail, the Netlify deploy still happen.

**Comment by smcgregor** [comment]
I believe production deploys should be blocked by test failures, but staging deploys should not be... Maybe we set it so that Netlify deploys `master` only when GitHub triggers it from a pipeline?

**Comment by cesarvarela** [comment]
We  need to complement this with specific settings on the repo:

- only collaborators should have access to Github secrets by default
- non-collaborators PRs should only run actions and access secrets after approval (looks like we need something like this: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks)
- there should be two sets of secrets, one for staging and one for production 

(looks like there was no need to merge to staging, because the action was created and ran anyway)

**Comment by cesarvarela** [comment]
closing in favor of #667

**Pull request closed without merging**
