### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
Included:

- subscribe button
- French
- small UI fixes
- improve incident updates handling
- fix truncated description
- fix taxonomies carousel
- NLP incident detection

To deploy:

Update on Netlify:  `GATSBY_AVAILABLE_LANGUAGES=en,es,fr` (`fr` added)

Deploy preview: https://staging-aiid.netlify.app/

### CODE REVIEW

**Comment by cesarvarela** [comment]
@smcgregor This is ready for review

**Comment by smcgregor** [comment]
Still working through this.

## Not blocking, but important

- [ ] The discover app doesn't have the footer.
- [ ] Links in the `Incidents similaires`...`Par similarité textuelle` block is not localizing, it lands in English
- [ ] The user needs information on what it means to subscribe to things. Do they get notifications when the incident gets a new report? Do they get updates when someone edits the incident?
- [ ] The user might not know that notifications are email notifications. Maybe add the email symbol to the buttons for subscriptions?
- [ ] While the user is being logged in to the app, you could prevent the jump showing the insertion of the button element by keeping the button on the page and making it inactive until the user status resolves.

**Comment by smcgregor** [comment]
- [ ] I think the entities page now has something weird happening in the bullets 
Screen Shot 2022-10-10 at 3 31 43 PM

**Comment by cesarvarela** [comment]
There is something going on with the candidates thing, tracking it here: https://github.com/responsible-ai-collaborative/aiid/issues/1241

**Comment by smcgregor** [comment]
- [ ] In mobile widths the tools break out of the panel on the citation page
Screen Shot 2022-10-10 at 5 21 35 PM

**Pull request merged**
