### PR TITLE
Collapsable Menu

### PR DESCRIPTION
**Pull request by lmcnulty**
https://user-images.githubusercontent.com/25443411/205158787-340d9908-18b7-4f5e-9a9e-5bf9f5a418d7.mp4

<details>
<summary>Old videos</summary>
https://user-images.githubusercontent.com/25443411/204391157-d3823d9f-5d32-4961-9746-37c610654129.mp4

https://user-images.githubusercontent.com/25443411/203854508-c0c8ef63-a79c-4783-8553-cbe475ef73e7.mp4
</details>

## Breakage Attempts
- Scroll to bottom and top with Home and End Keys
- Scroll slowly
- Scroll fast
- Zoom in
- Collapse the sidebar and zoom and the same time
- Scroll sidebar to bottom while zoomed in enough that not all items fit on the screen
- ^While sidebar is collapsed
- Hover icons for tooltips
- In mobile view
  - Use quick access buttons
  - Zoom
  - Scroll 
  - Hover nodes
  - Switch between mobile and desktop size
    - **Issue** (Non-blocking): Sometimes seems to break the hover styling of tree nodes

Also solves #1530.

### CODE REVIEW

**Review by cesarvarela — COMMENTED** [review]
The grey (gray?) background stops after the discover/submit buttons. Is it intentional?

image

(It looks weird to me the white background bleeding into the menu, but I can live with it)

**Comment by lmcnulty** [comment]
@cesarvarela Good point, fixed.

**Review by cesarvarela — CHANGES_REQUESTED** [review]
Looks like the Discover app layout broke:

image

**Comment by cesarvarela** [comment]
Asked the same in the other PR, which one is the chosen one? 
This or https://github.com/responsible-ai-collaborative/aiid/pull/1313

**Comment by smcgregor** [comment]
Functionally I think you have this tied up except the loading skeleton on the incidents table appears to be different in size: https://deploy-preview-1387--staging-aiid.netlify.app/apps/incidents

Once you take a look at that, I'll do a final code-level review before merging.

**Comment by smcgregor** [comment]
One last design feedback: When you hover for a moment over the icons it eventually gives you a tooltip, but I think it is a bit slow and this will confuse users a bit. As a design example, you can see below where the help message appears almost immediately. I think that is needed here when the panel is collapsed.

Screen Shot 2023-01-09 at 11 37 51 AM

I found a bug: it looks like there is a style issue on mobile. The text is rendered, but it is white on nearly-white.

**Comment by smcgregor** [comment]
It looks like the icons are not centering:

Screen Shot 2023-01-12 at 12 35 14 PM

**Comment by cesarvarela** [comment]
@lmcnulty please fix conflicts

**Comment by cesarvarela** [comment]
@lmcnulty please fix conflicts!

**Comment by cesarvarela** [comment]
image

**Comment by cesarvarela** [comment]
The failing test was just flake; I'll merge this after the current deployment to prod.

**Review by cesarvarela — APPROVED** [review]

**Pull request merged**
