### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**
- new Variants UX
- multiple incident linking on Submissions

### CODE REVIEW

**Comment by cesarvarela** [comment]
@smcgregor ready for review

The following pop-up text might need to be tweaked, lmk what you think:

image

**Comment by smcgregor** [comment]
Text is good.

@pdcp1 it looks like the deploy preview is up now? Good for final review?

**Comment by pdcp1** [comment]
@smcgregor Yes, it is good to review

**Comment by smcgregor** [comment]
Blocking

* Variants are rendering to the "Latest Incident" component on the landing page
* Let's also address [this](https://github.com/responsible-ai-collaborative/aiid/issues/1952) before deploying

Not Blocking

* Approved variants should be listed first

**Comment by pdcp1** [comment]
> Blocking
> 
> * Variants are rendering to the "Latest Incident" component on the landing page #1953 
> * Let's also address [this](https://github.com/responsible-ai-collaborative/aiid/issues/1952) before deploying
> 
> Not Blocking
> 
> * Approved variants should be listed first #1956

**Comment by cesarvarela** [comment]
@smcgregor ready for another review

**Comment by smcgregor** [comment]
Merging now! The only additional issue I surfaced in testing is the submit form state doesn't clear after submitting.

**Pull request merged**
