### PR TITLE
Fix SimilarIncidents styling

### LINKED ISSUE #1014: Too many similar incidents with large texts
[Incident 271](https://incidentdatabase.ai/cite/271) - Too many similar incidents with large title texts

image

### PR DESCRIPTION
**Pull request by lmcnulty**
Resolves #1014 and #971

image

### CODE REVIEW

**Comment by clari182** [comment]
Hey @lmcnulty looks good!
The only thing is that when the incident is "flaggable", the flag icon is missing some padding to the right.
image
I think this is quickly fixable by replacing `tw-mr-4` with `tw-pr-4` on line 50 of `SimilarIncidents.js` or a similar fix.

**Comment by lmcnulty** [comment]
@clari182 Good catch, thanks!

**Review by clari182 — APPROVED** [review]

**Comment by lmcnulty** [comment]
@clari182  Conflicts fixed. I also switched to absolute positioning on the subtitle so that the flags + dates on all of the cards are aligned when the titles have a different number of lines, and I added overflow: hidden so that the rounded corners on the top are visible.

image

**Comment by cesarvarela** [comment]
Please merge staging now that deploy finishes 🥳

**Comment by clari182** [comment]
@lmcnulty awesome! 
The only thing I'd change is the style of tw-card-set
from 
```
.tw-card-set {
    @apply tw-gap-4 tw-mb-8 tw-grid tw-grid-cols-1 1300px:tw-grid-cols-3;
}
```
to 
```
.tw-card-set {
    @apply tw-gap-4 tw-mb-8 tw-grid tw-grid-cols-1 md:tw-grid-cols-2 1300px:tw-grid-cols-3;
}
```
To add an additional breakpoint and display cards smaller when the view is not mobile.
Let me know if you agree!

**Comment by lmcnulty** [comment]
@clari182 Good idea, added. Thanks!

**Pull request merged**
