### PR TITLE
Deploy to Production

### PR DESCRIPTION
**Pull request by cesarvarela**

### CODE REVIEW

**Comment by cesarvarela** [comment]
Added a fix to the current production build

**Comment by cesarvarela** [comment]
@clari182 I think we might not need the `customTypesApiToken` since we are copy-pasting custom types definitions instead of hitting the API directly, but please confirm.

**Comment by cesarvarela** [comment]
@smcgregor this should fix the current production build

**Comment by smcgregor** [comment]
@Janetbananet you were wanting a final update to the blog content. Do you have an ETA on that? Can we deploy, content wise?

**Comment by Janetbananet** [comment]
I updated the verbiage in Prismic Staging yesterday (saved, not published), but I believe @clari182 was going to help move it across the finish line today since she knows more about your current deploy processes and how that integrates with Prismic.

**Comment by clari182** [comment]
@cesarvarela the `customTypesApiToken` is required for the `gatsby-source-prismic` plugin to fetch the custom types. Otherwise we'd need to define them inside the code as well (as a schema).
@Janetbananet I triggered the deploy to staging with your prismic updates. It looked good to me!

**Pull request merged**
