### PR TITLE
Feature/incidents carousel

### LINKED ISSUE #969: Landing page should have row of incidents
Essentially replacing the "Latest incident report" with a row of items from Discover. Could be a carousel.

### PR DESCRIPTION
**Pull request by clari182**
- closes #969 

Loads the latest 5 incidents inside a carousel

### CODE REVIEW

**Review by lmcnulty — COMMENTED** [review]
This looks good, but I think we should constrain it so there can be only one report in the carousel per incident. When I run it with my dev db every report is for the same incident.

**Review by cesarvarela — COMMENTED** [review]
I would make the arrows consistent:

image

**Comment by cesarvarela** [comment]
@clari182 conflicts!

**Comment by clari182** [comment]
@cesarvarela ready for another review

**Review by cesarvarela — COMMENTED** [review]
Should this show the latest 5?

**Pull request merged**
