### PR TITLE
Feature video support

### PR DESCRIPTION
**Pull request by cesarvarela**
Adds a new `video_url` field to reports:

Submission form: 

image

When editing a submission:

image

Citation page:

image

Editing a report:

image

It can be tested here: https://deploy-preview-53--cesarvarela-staging.netlify.app/

### CODE REVIEW

**Comment by cesarvarela** [comment]
@smcgregor you can test the feature in the link above.

**Comment by smcgregor** [comment]
@cesarvarela I think this is looking good. Can you DM me a user/password and I'll share it with editors that want to give it a test run?

**Comment by cesarvarela** [comment]
@smcgregor sent

**Comment by clari182** [comment]
Hey @cesarvarela I get this error trying to load a video:
image
image

It looks like it only happens on specific video URLs. This is the one I'm testing: https://www.youtube.com/watch?v=eDNjeTwGi5E
Maybe on the error message we can add that the video cannot be seen inside a preview.

Otherwise, the code looks good!

**Comment by cesarvarela** [comment]
I'll check if I can show a custom error message for that case 👍

**Comment by cesarvarela** [comment]
@kepae, what should I do with this one?

cc @smcgregor

**Pull request closed without merging**
